//Material System Types
export const SET_GOODS_INSPECTION_VOUCHER = "SET_GOODS_INSPECTION_VOUCHER"
export const SET_GOODS_RECEIPT_VOUCHER = "SET_GOODS_RECEIPT_VOUCHER"
export const SET_PURCHASE_ORDER_AMENDMENT = "SET_PURCHASE_ORDER_AMENDMENT"
export const SET_PURCHASE_ORDER = "SET_PURCHASE_ORDER"
export const SET_PURCHASE_REQUEST = "SET_PURCHASE_REQUEST"
export const WAREHOUSE_RECEIPT_VOUCHER = "WAREHOUSE_RECEIPT_VOUCHER"
